# Generated by Django 3.2.23 on 2023-12-16 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0003_delete_apointment'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='apointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(auto_now_add=True)),
                ('reason', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('scheduled', 'scheduled'), ('canceled', 'canceled'), ('completed', 'completed')], default='scheduled', max_length=9)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorinfo')),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientinfo')),
            ],
        ),
    ]
