# Generated by Django 3.2.23 on 2023-12-16 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_apointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='apointment',
        ),
    ]
